version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: parser
      MYSQL_DATABASE: ef_parser
      MYSQL_USER: logs
      MYSQL_PASSWORD: logs
