debug: false

spring:
  profiles.active: default
  batch:
    initialize-schema: always
  datasource:
    initialization-mode: always

---
spring:
  profiles: default

  datasource:
    url: jdbc:mysql://localhost:3306/ef_parser
    username: logs
    password: logs

